App 2290 migrate icon
viamrobotics/prime pull request #301
Opened 2023-08-03 15:33 UTC by mrloureed

Add icons to Prime core package

<img width="335" alt="image" src="https://github.com/viamrobotics/prime/assets/17263/a92e94e2-ec6f-45a0-acee-5bed28de6d17">

https://viam.atlassian.net/browse/APP-2290

2023-08-03 15:43 UTC, micheal-parks commented on packages/core/package.json
> +    "@mdi/js": "^7.2.96"
Should be a devDependency

2023-08-03 15:45 UTC, micheal-parks commented on packages/core/src/lib/icon/icons.ts
> +import {
up for switching to a wildcard import here?

```ts
import * as MDI from from '@mdi/js';

export const paths: Record<string, string> = {
  alert: MDI.mdiAlert,
  ...

2023-08-03 15:45 UTC, micheal-parks commented on packages/legacy/src/elements/select/select.svelte
> +          class={cx('gextext-xs', {
typo?

2023-08-03 16:13 UTC, ethanlook reviewed
Do you mind adding the new story to packages/storybook?

2023-08-03 16:13 UTC, ethanlook commented on packages/core/src/lib/icon.spec.ts
Could you please put this in the icon directory?

2023-08-03 17:32 UTC, ethanlook requested changes
Do you mind adding a new story to package/storybook? We're also migrating the storybook as we go.

2023-08-03 17:32 UTC, ethanlook commented on packages/core/src/lib/icon/icon.svelte
> +/**
Non-exported variables do not need a docstring unless it makes the code more readable. I think the docstring is unnecessary in the case of Size, hasNameProperty, and sizes, but it's ultimately up to you.

2023-08-03 22:02 UTC, mrloureed commented
> Do you mind adding a new story to package/storybook? We're also migrating the storybook as we go.

Added . Could def be improved but shows some icons . Can do more when I return from vaca.

2023-08-04 13:16 UTC, ethanlook approved these changes

2023-08-07 18:06 UTC, merged